# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test iOS Project
    runs-on: macos-latest  # Use the latest macOS runner

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Xcode environment (Optional but recommended)
    - name: Set up Xcode
      uses: macos-actions/setup-xcode@v1
      with:
        xcode-version: '14.0'  # Specify the Xcode version you are using

    # Step 3: Install dependencies (CocoaPods, Carthage, SwiftPM, etc.)
    - name: Install dependencies
      run: |
        if [ -f Podfile ]; then
          echo "Installing CocoaPods dependencies"
          sudo gem install cocoapods
          pod install
        fi
        # Add other dependency managers (like Carthage or SwiftPM) if needed.

    # Step 4: Build the project
    - name: Build the iOS project
      run: |
        xcodebuild -workspace YourWorkspace.xcworkspace -scheme YourScheme -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' clean build

    # Step 5: Run tests
    - name: Run tests
      run: |
        xcodebuild test -workspace YourWorkspace.xcworkspace -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 14'
    
    # Step 6: Upload test results (optional)
    - name: Upload test results
      if: success() || failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/logs
