# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test iOS Project
    runs-on: macos-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Xcode version (optional)
    - name: Set up Xcode 15 (or any compatible version)
      run: |
        sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        if [ -f Podfile ]; then
          echo "Installing CocoaPods dependencies"
          sudo gem install cocoapods
          pod install
        fi

    # Step 4: Build the project using hardcoded .xcodeproj path
    - name: Build the iOS project
      run: |
        echo "Building with .xcodeproj"
        xcodebuild -project "./Expense Tracker.xcodeproj" -scheme "Expense Tracker" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' clean build

    # Step 5: Run tests using hardcoded .xcodeproj path
    - name: Run tests
      run: |
        echo "Running tests..."
        xcodebuild test -project "./Expense Tracker.xcodeproj" -scheme "Expense Tracker" -destination 'platform=iOS Simulator,name=iPhone 14'

    # Step 6: Upload test results (optional)
    - name: Upload test results
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/logs
